### ISSUE TITLE
Error in Log after restarting / No media_player entity

### ISSUE THREAD

**Issue by AdmiralRaccoon** [xilense/aimp_custom_component#1]
Hello,
I´m getting the below error in the log after adding this code in the configuration.yaml and restarting HA, and the media_player antity will not be created.
I´m using AIMP for the first time, but I guess the setup is working, as I can open the webinterface with 192.168.1.14:3333 from a pc.

Any idea what I have done wrong? I´m using HA Core 2021.6.6
Thanks for help,
Philipp

```
media_player:   
  - platform: aimp
    name: AIMP Livingroom
    host: 192.168.1.14
    port: 3333
```

```
`2021-06-23 14:21:20 ERROR (MainThread) [homeassistant.components.media_player] aimp: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aimp/media_player.py", line 144, in update
    self.update_playinfo()
  File "/config/custom_components/aimp/media_player.py", line 169, in update_playinfo
    self._playinfo = resp.copy()
AttributeError: 'NoneType' object has no attribute 'copy'`
```

**Comment by AdmiralRaccoon** [comment]
Oh wait, never mind, I have rerun the settingsmanager from the control plugin and applied some missing checkboxes.
Now I can see the entity in HA

**Comment by xilense** [comment]
glad to hear the issue has resolved
